class_name TileType
extends Node

const NORTH_SIDE = 0
const SOUTH_SIDE = 1
const EAST_SIDE = 2
const WEST_SIDE = 3

# CORNER TILES
const NORTH_WEST_CORNER = 4
const NORTH_EAST_CORNER = 5
const SOUTH_WEST_CORNER = 6
const SOUTH_EAST_CORNER = 7

# NARROW TILES
const NORTH_SOUTH_STRAIGHT = 8
const EAST_WEST_STRAIGHT = 9

# DEAD END TILES
const NORTH_DEADEND = 10
const SOUTH_DEADEND = 11
const EAST_DEADEND = 12
const WEST_DEADEND = 13

const CENTRE = 14

const ENCLOSED = 15
